export const privacyPolicyData = {
  lastUpdated: "August 3, 2026",
  companyName: "BeonicX",
  website: "https://www.beonicx.com",
  contactEmail: "privacy@beonicx.com",

  sections: [
    {
      title: "Introduction",
      content:
        "BeonicX ('we', 'our', or 'us') is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website, use our AI-powered products, SaaS platforms, or engage with our services. By accessing or using our services, you agree to this Privacy Policy.",
    },
    {
      title: "Information We Collect",
      subsections: [
        {
          subtitle: "Personal Information",
          items: [
            "Name, email address, phone number, and company name",
            "Billing and payment information",
            "Account credentials (username and encrypted password)",
            "Professional title and business address",
            "Communication preferences",
          ],
        },
        {
          subtitle: "Usage and Technical Data",
          items: [
            "IP address, browser type, device information, and operating system",
            "Pages visited, time spent, clickstream data, and referral URLs",
            "Feature usage patterns and interaction data within our SaaS platforms",
            "API call logs, query metadata, and service usage metrics",
            "Cookies, pixel tags, and similar tracking technologies",
          ],
        },
        {
          subtitle: "AI-Specific Data",
          items: [
            "Input data provided to our AI models (prompts, queries, uploaded files)",
            "Output data generated by our AI systems",
            "Feedback and ratings provided on AI-generated outputs",
            "Model interaction history and session data",
          ],
        },
      ],
    },
    {
      title: "How We Use Your Information",
      items: [
        "To provide, maintain, and improve our AI and SaaS services",
        "To process transactions and send related information",
        "To personalize your experience and deliver relevant content",
        "To train and improve our AI models (only with anonymized and aggregated data unless you explicitly opt in)",
        "To communicate with you about updates, security alerts, and support",
        "To detect, prevent, and address technical issues, fraud, or security threats",
        "To comply with legal obligations and enforce our terms of service",
        "To conduct analytics and research to enhance our products",
      ],
    },
    {
      title: "AI Data Processing",
      content:
        "We take special care with data processed by our AI systems. Your input data is processed to generate outputs and improve service quality. We do not use your personal or proprietary input data to train AI models shared with other customers unless you provide explicit consent. You retain ownership of your input data and any outputs generated specifically for you.",
      items: [
        "Input data is encrypted in transit and at rest",
        "AI processing occurs on secure, isolated infrastructure",
        "You can request deletion of your AI interaction history at any time",
        "We do not sell AI-generated insights derived from your data to third parties",
        "Automated decision-making is disclosed where applicable, and you may request human review",
      ],
    },
    {
      title: "Data Sharing and Disclosure",
      content:
        "We do not sell your personal information. We may share your data in the following circumstances:",
      items: [
        "With service providers who assist in operating our platform (hosting, analytics, payment processing) under strict confidentiality agreements",
        "With your consent or at your direction",
        "To comply with legal requirements, court orders, or government requests",
        "To protect the rights, property, or safety of BeonicX, our users, or the public",
        "In connection with a merger, acquisition, or sale of assets (with prior notice to you)",
      ],
    },
    {
      title: "Data Retention",
      content:
        "We retain your personal information only for as long as necessary to fulfill the purposes outlined in this policy, unless a longer retention period is required by law. Account data is retained for the duration of your active account and for up to 30 days after deletion request. AI interaction logs are retained for up to 90 days for service improvement purposes unless you request earlier deletion.",
    },
    {
      title: "Data Security",
      content:
        "We implement industry-standard security measures to protect your information:",
      items: [
        "AES-256 encryption for data at rest and TLS 1.3 for data in transit",
        "Regular security audits and penetration testing",
        "Role-based access controls and multi-factor authentication",
        "SOC 2 Type II compliance and regular third-party assessments",
        "Incident response procedures with notification within 72 hours of a confirmed breach",
      ],
    },
    {
      title: "Your Rights and Choices",
      content:
        "Depending on your jurisdiction, you may have the following rights:",
      items: [
        "Access: Request a copy of the personal data we hold about you",
        "Correction: Request correction of inaccurate or incomplete data",
        "Deletion: Request deletion of your personal data ('Right to be Forgotten')",
        "Portability: Receive your data in a structured, machine-readable format",
        "Objection: Object to processing of your data for certain purposes",
        "Restriction: Request restricted processing of your data",
        "Withdraw Consent: Withdraw previously given consent at any time",
        "Opt-Out of AI Training: Opt out of having your data used for AI model improvement",
      ],
    },
    {
      title: "Cookies and Tracking",
      content:
        "We use cookies and similar technologies to enhance your experience. You can manage your cookie preferences through your browser settings or our cookie consent banner.",
      subsections: [
        {
          subtitle: "Types of Cookies We Use",
          items: [
            "Essential Cookies: Required for basic site functionality",
            "Analytics Cookies: Help us understand how visitors interact with our site",
            "Functional Cookies: Remember your preferences and settings",
            "Marketing Cookies: Used to deliver relevant advertisements (only with consent)",
          ],
        },
      ],
    },
    {
      title: "International Data Transfers",
      content:
        "Your information may be transferred to and processed in countries other than your country of residence. We ensure appropriate safeguards are in place, including Standard Contractual Clauses (SCCs) approved by relevant authorities, to protect your data during international transfers.",
    },
    {
      title: "Children's Privacy",
      content:
        "Our services are not directed to individuals under the age of 16. We do not knowingly collect personal information from children. If we become aware that we have inadvertently collected data from a child, we will take steps to delete it promptly.",
    },
    {
      title: "Third-Party Links",
      content:
        "Our services may contain links to third-party websites or services. We are not responsible for the privacy practices of these third parties. We encourage you to review their privacy policies before providing any personal information.",
    },
    {
      title: "Changes to This Policy",
      content:
        "We may update this Privacy Policy from time to time. We will notify you of material changes by posting the updated policy on our website with a revised 'Last Updated' date, and where required by law, through email notification. Continued use of our services after changes constitutes acceptance of the updated policy.",
    },
    {
      title: "Contact Us",
      content:
        "If you have questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:",
      contactInfo: {
        email: "privacy@beonicx.com",
        address: "BeonicX Technologies Pvt. Ltd.",
        dpo: "Data Protection Officer, BeonicX",
      },
    },
  ],
};
